url: "https://ningding97.github.io/ultrtaproject_website/"
title: UltraProject
subtitle: Scaling simple ideas.
# google_analytics_tracking_id: UA-12450662-3
permalink: /blog/:year/:month/:day/:title/
blog_baseurl: "/blog/" # the subpath of your site, e.g. /blog/
# twitter_username: ArtsyOpenSource
# github_username: Artsy
baseurl: "/ultrtaproject_website"

subscribe_rss: /feed.xml

# disqus_short_name: artsy
# disqus_show_comment_count: false

exclude: ["vendor", "LICENSE", "_posts/LICENSE"]

plugins: ["jekyll-redirect-from", "jekyll-paginate"]

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

paginate: 10
paginate_path: "/blog/:num/"

recent_posts: 5
excerpt_link: "Read More"
titlecase: true
category_dir: blog/categories

authors:
  orta:
    name: Orta Therox
    site: http://orta.io
    twitter: orta
    github: orta
    byline: Code Janitor at Artsy, thinking about JS tooling.

  db:
    name: Daniel Doubrovkine
    site: http://code.dblock.org
    twitter: dblockdotorg
    github: dblock

  ash:
    name: Ash Furrow
    github: ashfurrow
    twitter: ashfurrow
    site: http://ashfurrow.com

  lily:
    name: Lily Pace
    github: lilyfromseattle
    twitter: lilyfromseattle
    site: http://lilyfromseattle.com

series:
  - title: "React Native at Artsy"
    url: series/react-native-at-artsy/
  - title: "JavaScriptures"
    url: series/javascriptures/
  - title: "Stages of Professional Growth"
    url: series/stages-of-professional-growth/
  - title: "Artsy Tech Stack"
    url: series/artsy-tech-stack/
  - title: "Open Source by Default"
    url: series/open-source-by-default/

oss_projects:
  - title: Enhancing Chat Language Models by Scaling High-quality Instructional Conversations (EMNLP 2023)
    # svg: "_includes/svg/force.svg"
    description:
      We introduce UltraChat, a large-scale dataset designed for training AI assistants, 
      featuring 1.5 million high-quality, diverse multi-turn dialogues without human queries. 
      Leveraging UltraChat, we fine-tuned a LLaMA model to create UltraLM, a powerful conversational model. 

    category: project
    github: https://github.com/thunlp/UltraChat
    arxiv: https://arxiv.org/abs/2305.14233
    created: Apr 3rd, 2023

  - title: Boosting Language Models with High-quality Feedback (ICLR 2024)
    description:
      We introduce UltraFeedback, a large-scale, diversified dataset enhancing Reinforcement Learning from Human Feedback 
      (RLHF) in language models. Addressing the scarcity of diverse preference data, 
      it combines various instructions and models for comparative data. 
      We trained models like UltraRM, UltraLM-13B-PPO, and UltraCM using it.

    category: project
    github: https://github.com/OpenBMB/UltraFeedback
    arxiv: https://arxiv.org/abs/2310.01377
    created: Sep 7th, 2023

  - title: UltraChat-1.5M
    description:
      The React component library shared across our web applications, letting us share expertise and experience
      across engineering teams. Built on top of our project Palette.
    category: dataset
    huggingface: https://huggingface.co/datasets/stingning/ultrachat
    created: Apr 7th, 2023

  - title: UltraFeedback-64k
    description:
      The React component library shared across our web applications, letting us share expertise and experience
      across engineering teams. Built on top of our project Palette.
    category: dataset
    huggingface: https://huggingface.co/datasets/openbmb/UltraFeedback
    created: Sep 7th, 2023

  - title: UltraEval
    description:
      UltraEval is an open-source framework for evaluating the capabilities of foundation models, 
      providing a suite of lightweight, easy-to-use evaluation systems that support the performance 
      assessment of mainstream LLMs.
    category: project
    website: https://ultraeval.openbmb.cn/rank
    github: https://github.com/OpenBMB/UltraEval
    created: Nov 24th, 2023

  - title: UltraLM-13B
    description:
      First version of UltraLM, finetuned with UltraChat dataset on Llama-13B. Ranked 1 on AlpacaEval on Jun 28.
    category: model
    huggingface: https://huggingface.co/openbmb/UltraLM-13b
    created: Jun 3rd, 2023

  - title: UltraLM-13B-v2.0
    # svg: "_includes/svg/eigen.svg"
    description:
      Second version of UltraLM, finetuned with UltraChat dataset on Llama2-13B and aligned with RL by UltraFeedback. 
      Ranked 1 on AlpacaEval on Nov 28.
    category: model
    huggingface: https://huggingface.co/openbmb/UltraLM-13b-v2.0
    created: Sep 18th, 2023

  - title: UltraLM-65B
    # svg: "_includes/svg/eidolon.svg"
    description: 
      Finetuned with UltraChat dataset on Llama-65B.
    category: model
    huggingface: https://huggingface.co/openbmb/UltraLM-65b
    created: Aug 3rd, 2014

  - title: Falcon-180b-Chat
    # svg: "_includes/svg/energy.svg"
    description:
      Falcon-180B-Chat is a 180B parameters causal decoder-only model built by 
      TII based on Falcon-180B and finetuned on a mixture of Ultrachat, Platypus and Airoboros.
    category: community
    huggingface: https://huggingface.co/tiiuae/falcon-180B-chat
    created: Sep 4th, 2023

  - title: Zephyr-7B
    # svg: "_includes/svg/emergence.svg"
    description: 
      Zephyr is a series of language models that are trained to act as helpful assistants. 
      Zephyr-7B-Î² is the second model in the series, and is a fine-tuned version of mistralai/Mistral-7B-v0.1 
      that was trained on on a mix of publicly available, synthetic datasets using Direct Preference Optimization (DPO). 
    category: community
    huggingface: https://huggingface.co/HuggingFaceH4/zephyr-7b-beta
    created: Nov 22nd, 2023


student_members:
  - name: Ning Ding
    github: ningding97
    website: https://www.stingning.cn/
    affiliation: Tsinghua University
  
  - name: Ganqu Cui
    affiliation: Tsinghua University
  
  - name: Shengding Hu
    affiliation: Tsinghua University

  - name: Yulin Chen
    affiliation: Tsinghua University

  - name: Chaoqun He
    affiliation: Tsinghua University

  - name: Lifan Yuan
    affiliation: Tsinghua University

  - name: Bokai Xu
    github: bokesyo
    website: https://bokaixu.site
    affiliation: CUHK(Shenzhen)
  
  - name: Yujia Qin
    affiliation: Tsinghua University
  
  - name: Zhi Zheng
    affiliation: Tsinghua University

  - name: Guanming Yao
    affiliation: Tsinghua University & ModelBest Inc

  - name: Wei Zhu
    affiliation: PingAn Technology & East China Normal University

  - name: Yuan Ni
    affiliation: PingAn Technology

  - name: Guotong Xie
    affiliation: PingAn Technology

faculty_members:
  - name: Zhiyuan Liu
    affiliation: Tsinghua University

  - name: Maosong Sun
    affiliation: Tsinghua University

  - name: Bowen Zhou
    affiliation: Tsinghua University
  